#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/bitnet/modular_bitnet.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_bitnet.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The BitNet Team and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and

from typing import Callable, Optional, Tuple, Union
import time
import torch
from torch import nn

# --- MODIFIED IMPORTS START ---
from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache, StaticCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.modeling_attn_mask_utils import AttentionMaskConverter
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs

#from transformers.modeling_utils import GradientCheckpointingLayer
GradientCheckpointingLayer = nn.Module

from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import (
    LossKwargs,
    add_start_docstrings,
    add_start_docstrings_to_model_forward,
    can_return_tuple,
    is_torch_flex_attn_available,
    logging,
    replace_return_docstrings,
)

# This imports the official config from the library
from transformers import BitNetConfig


if is_torch_flex_attn_available():
    from torch.nn.attention.flex_attention import BlockMask
    from transformers.integrations.flex_attention import make_flex_block_causal_mask
# --- MODIFIED IMPORTS END ---
import globVR
import glob_set



logger = logging.get_logger(__name__)
_CONFIG_FOR_DOC = "BitNetConfig"


@use_kernel_forward_from_hub("RMSNorm")
class BitNetRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        BitNetRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class BitNetMLP(nn.Module):
    def __init__(self, config: BitNetConfig):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]
        self.ffn_sub_norm = BitNetRMSNorm(config.intermediate_size, eps=config.rms_norm_eps)

    def forward(self, x):
        down_proj = self.down_proj(self.ffn_sub_norm(self.act_fn(self.gate_proj(x)) * self.up_proj(x)))
        return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights

class BitNetAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: BitNetConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True
        self.num_heads = config.num_attention_heads
        self.num_kv_heads = config.num_key_value_heads

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        self.attn_sub_norm = BitNetRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
    
    def apply_attn_mask(self, attn_score, w_blk, w_sink):
        bsz, n_heads, row, col = attn_score.shape
        mask = torch.zeros(attn_score.shape, dtype=torch.bfloat16).cuda()
        for i in range(row):
            mask[:,:,i, 0:w_sink] = 1
            block_start = (i//w_blk)*w_blk
            mask[:,:,i, block_start:block_start+w_blk] = 1
        attn_out = attn_score * mask
        return attn_out
    
    def get_delta_mat(self, input_states, thresh):
        # Compute the delta matrix of the input states
        # input_states: input matrix to get delta
        # thresh: threshold to determine delta
        # delta_all : size(bs, num_heads, seq_len, head_dim/seq_len)
        bsz, n_head, seq_len, head_dim = input_states.shape
        input_old = input_states[:,:,0:1,:] # size:(bsz, num_heads, head_dim/seq_len)

        # delta_all = torch.zeros(1,self.num_heads,1,mat_len, dtype=torch.float16).cuda()
        delta_all = input_old
        # delta_mask_all = torch.tensor([]).cuda()
        # compute the delta matrix for the query
        for n in range(1, seq_len):
            input_new = input_states[:,:,n:n+1,:]
            sub = input_new - input_old #size:(bsz, num_heads, 1, head_dim/seq_len)
            # sub = quantize_tensor(sub, 1, 7, globVR.quant_on)
            sub_pos = sub.abs()
            delta_mask = sub_pos <= thresh
            delta_row = sub.masked_fill_(delta_mask,0) #.view(bsz,n_head,1,head_dim)
            delta_all = torch.cat((delta_all, delta_row), dim=2)
            input_old = torch.where(delta_mask, input_old, input_new)
        
        return delta_all

    def get_row_delta_mat(self, input_states, threshold, similarity_metric="cosine"):
        """
        Computes a row-wise (structured) delta matrix and a keep-mask.
        OPTIMIZED FOR SPEED: Does not zero-out skipped rows.
        """
        bsz, n_head, seq_len, head_dim = input_states.shape
        device = input_states.device
        
        # 1. OPTIMIZATION: Use empty_like to skip the massive zero-initialization overhead
        delta_all = torch.empty_like(input_states)
        
        # Initialize the Boolean Map
        keep_mask = torch.zeros((bsz, n_head, seq_len), dtype=torch.bool, device=device)
        
        # --- FIRST TOKEN HANDLING ---
        delta_all[:, :, 0, :] = input_states[:, :, 0, :]
        keep_mask[:, :, 0] = True
        
        # Initialize reference states
        ref_states = input_states[:, :, 0, :].clone() 

        for n in range(1, seq_len):
            current_row = input_states[:, :, n, :]
            
            # --- METRIC CALCULATION ---
            # Directly calculating `should_keep` to avoid extra NOT operations
            if similarity_metric == "cosine":
                sim = torch.nn.functional.cosine_similarity(current_row, ref_states, dim=-1)
                should_keep = sim < threshold
                
            elif similarity_metric == "euclidean":
                # OPTIMIZATION: Squared distance is much faster than torch.norm (which does a sqrt)
                sq_dist = torch.sum((current_row - ref_states) ** 2, dim=-1)
                should_keep = sq_dist > (threshold ** 2)
                
            elif similarity_metric == "l1":
                dist = torch.norm(current_row - ref_states, p=1, dim=-1)
                should_keep = dist > threshold
                
            elif similarity_metric == "max":
                dist = torch.max(torch.abs(current_row - ref_states), dim=-1)[0]
                should_keep = dist > threshold

            elif similarity_metric == "kl":
                p = torch.nn.functional.softmax(current_row, dim=-1)
                q = torch.nn.functional.softmax(ref_states, dim=-1)
                kl_div = torch.sum(p * (torch.log(p + 1e-10) - torch.log(q + 1e-10)), dim=-1)
                should_keep = kl_div > threshold
                
            else:
                raise ValueError(f"Unknown metric: {similarity_metric}")

            # --- MASK GENERATION ---
            keep_mask[:, :, n] = should_keep

            # --- DELTA CALCULATION ---
            # OPTIMIZATION: Unconditionally write the delta. 
            # We removed torch.where() and torch.zeros_like().
            delta_all[:, :, n, :] = current_row - ref_states
            
            # --- REFERENCE UPDATE ---
            # Update reference ONLY if the row was significant enough to be kept
            mask_broadcast = should_keep.unsqueeze(-1)
            ref_states = torch.where(mask_broadcast, current_row, ref_states)
            
        return delta_all, keep_mask
    
    def get_row_delta_mat_fast(self, input_states, threshold, similarity_metric="cosine"):
        bsz, n_head, seq_len, head_dim = input_states.shape
        device = input_states.device
        
        # Pre-allocate mask
        keep_mask = torch.zeros((bsz, n_head, seq_len), dtype=torch.bool, device=device)
        keep_mask[:, :, 0] = True
        
        # List accumulation for Eager Mode speed
        delta_list = [input_states[:, :, 0, :]]
        ref_states = input_states[:, :, 0, :].clone() 

        # Pre-compute threshold for euclidean to avoid squaring in the loop
        thresh_sq = threshold ** 2 if similarity_metric == "euclidean" else None

        for n in range(1, seq_len):
            current_row = input_states[:, :, n, :]
            
            # Compute diff ONCE. We use this for the delta list, and for L1/Max/Euclidean metrics.
            diff = current_row - ref_states
            
            # --- METRIC CALCULATION ---
            if similarity_metric == "cosine":
                sim = torch.nn.functional.cosine_similarity(current_row, ref_states, dim=-1)
                should_keep = sim < threshold
                
            elif similarity_metric == "euclidean":
                # Reusing 'diff', and doing element-wise multiplication instead of **2
                sq_dist = torch.sum(diff * diff, dim=-1)
                should_keep = sq_dist > thresh_sq
                
            elif similarity_metric == "l1":
                # Reusing 'diff', and using sum(abs) which is generally faster than torch.norm
                dist = torch.sum(torch.abs(diff), dim=-1)
                should_keep = dist > threshold
                
            elif similarity_metric == "max":
                # Reusing 'diff'
                dist = torch.max(torch.abs(diff), dim=-1)[0]
                should_keep = dist > threshold

            elif similarity_metric == "kl":
                p = torch.nn.functional.softmax(current_row, dim=-1)
                q = torch.nn.functional.softmax(ref_states, dim=-1)
                kl_div = torch.sum(p * (torch.log(p + 1e-10) - torch.log(q + 1e-10)), dim=-1)
                should_keep = kl_div > threshold
                
            else:
                raise ValueError(f"Unknown metric: {similarity_metric}")

            # --- MASK & DELTA ---
            keep_mask[:, :, n] = should_keep
            delta_list.append(diff)
            
            # --- REFERENCE UPDATE ---
            ref_states = torch.where(should_keep.unsqueeze(-1), current_row, ref_states)
            
        # Combine efficiently at the end
        delta_all = torch.stack(delta_list, dim=2)
        
        return delta_all, keep_mask
    
    
    
    def direct_prune(self, input_states, thresh):
        # mask = input_states > thresh
        out = torch.where(input_states.abs() < thresh, torch.tensor(0), input_states)
        globVR.direct_spars += torch.sum(out == 0).item()/out.numel()
        return out
    
    # def get_condition_mask(self, shape):
    #     # generate the A-shape condition matrix according to predefined window size and sink size
    #     bsz, n_heads, row, col = shape
    #     condition_mat = torch.zeros(shape, dtype=torch.bool).cuda()
    #     for i in range(row):
    #         condition_mat[:,:,i, 0:globVR.sink_size] = True
    #         if globVR.block_size > 0:
    #             block_start = (i//globVR.block_size)*globVR.block_size
    #             condition_mat[:,:,i, block_start:block_start+globVR.block_size] = True
    #         # condition_mat[:,:,i, max(0, i-globVR.window_size):i+1] = True
    #     return condition_mat
    
    # def regular_delta_mm_pattern(self, delta_y, regular_x, regular_y, bsz, seq_len, dim_out):
    #     delta_out = torch.matmul(regular_x, delta_y)
    #     output_base = delta_out[:,:,:,0].view(bsz,self.num_heads,dim_out, 1)
    #     out = output_base
    #     for pos in range(1, seq_len):
    #         output_base = output_base + delta_out[:,:,:,pos].view(bsz, self.num_heads, dim_out, 1)
    #         out = torch.cat((out, output_base), dim=-1)

    #     full_attn = torch.matmul(regular_x, regular_y)
    #     condition_mask = self.get_condition_mask(delta_out.shape)
    #     output = torch.where(condition_mask, full_attn, out)
    #     return output

    def get_condition_mask_dn(self, shape, blk_size):
        # generate the A-shape condition matrix according to predefined window size and sink size
        bsz, n_heads, row, col = shape
        condition_mat = torch.zeros(shape, dtype=torch.bool).cuda()
        for i in range(row):
            condition_mat[:,:,i, 0:globVR.sink_size] = True
            if blk_size > 0:
                block_start = (i//blk_size)*blk_size
                condition_mat[:,:,i, block_start:block_start+blk_size] = True
            # condition_mat[:,:,i, max(0, i-globVR.window_size):i+1] = True
        return condition_mat


    def _patch_hybrid_attention(self, out, regular_x, regular_y, bsz, seq_len, blk_size):
        """
        Efficiently computes exact attention ONLY for the Sink and Local Diagonal Blocks,
        patching them directly into the 'out' tensor.
        
        Args:
            out: (B, H, L, L) - The accumulated delta attention scores (to be patched)
            regular_x: (B, H, L, D) - Query states
            regular_y: (B, H, D, L) - Transposed Key states
        """
        # 
        
        sink_size = globVR.sink_size
        
        # --- A. SINK ATTENTION (Vertical Strip) ---
        # Computes attention from ALL tokens to the first 'sink_size' tokens.
        # Complexity: O(L * sink_size)
        if sink_size > 0:
            # 1. Slice K to get only sink columns: (B, H, D, sink_size)
            # We slice the last dimension of transposed K
            k_sink = regular_y[..., :sink_size]
            
            # 2. Compute exact scores: Q(All) * K(Sink)
            # Output: (B, H, L, sink_size)
            sink_scores = torch.matmul(regular_x, k_sink)
            
            # 3. Patch: Overwrite the first 'sink_size' columns of 'out'
            out[..., :sink_size] = sink_scores

        # --- B. LOCAL BLOCK ATTENTION (Diagonal Squares) ---
        # Computes attention within local blocks (e.g. 64x64 squares on diagonal).
        # Complexity: O(L * blk_size) -> Linear scaling with sequence length!
        if blk_size > 0:
            n_blocks = seq_len // blk_size
            trunc_len = n_blocks * blk_size
            
            if n_blocks > 0:
                # 1. Reshape Q to isolate blocks: (B, H, n_blocks, blk_size, D)
                q_blocked = regular_x[..., :trunc_len, :].view(bsz, self.num_heads, n_blocks, blk_size, -1)
                
                # 2. Reshape K (Transposed) to isolate blocks
                # K is (B, H, D, L) -> view as (B, H, D, n_blocks, blk_size)
                k_blocked = regular_y[..., :trunc_len].view(bsz, self.num_heads, -1, n_blocks, blk_size)
                # Permute to (B, H, n_blocks, D, blk_size) for batch matmul
                k_blocked = k_blocked.permute(0, 1, 3, 2, 4)

                # 3. Batch Matrix Multiplication
                # Computes all diagonal blocks in parallel
                # (..., blk, D) @ (..., D, blk) -> (..., blk, blk)
                block_scores = torch.matmul(q_blocked, k_blocked)
                
                # 4. Patch into 'out'
                # We view 'out' as a grid of blocks to easily assign to the diagonal
                out_view = out[..., :trunc_len, :trunc_len].view(bsz, self.num_heads, n_blocks, blk_size, n_blocks, blk_size)
                
                # Loop through blocks to assign diagonal: out[b,h,i,:,i,:] = block_scores[b,h,i,:,:]
                # Note: A Python loop here is fine because n_blocks is small (e.g. 16 for L=1024)
                for i in range(n_blocks):
                    out_view[:, :, i, :, i, :] = block_scores[:, :, i, :, :]

            # 5. Handle Remainder (Tail of sequence)
            # If L=100 and blk=64, we have 36 tokens left at the end.
            if seq_len > trunc_len:
                q_tail = regular_x[..., trunc_len:, :]     # (B, H, rem, D)
                k_tail = regular_y[..., trunc_len:]        # (B, H, D, rem)
                
                tail_scores = torch.matmul(q_tail, k_tail) # (B, H, rem, rem)
                
                # Patch the bottom-right corner
                out[..., trunc_len:, trunc_len:] = tail_scores

        return out

    def regular_delta_mm_pattern_dn(self, delta_y, regular_x, regular_y, bsz, seq_len, dim_out, blk_size, keep_mask=None):
            
            # --- OPTIMIZED PATH ---
            delta_out = torch.zeros(bsz, self.num_heads, seq_len, seq_len, 
                                dtype=regular_x.dtype, device=regular_x.device)

            if keep_mask is not None:
                for b in range(bsz):
                    for h in range(self.num_heads):
                        kv_head_idx = h // self.num_key_value_groups
                        mask_h = keep_mask[b, kv_head_idx]

                        # --- ADD THIS DEBUG PRINT ---
                        if b == 0 and h == 0:
                            active_ratio = mask_h.sum().item() / mask_h.numel()
                            # print(f"DEBUG: Head 0 Sparsity: {1.0 - active_ratio:.2%} (Active Rows: {mask_h.sum().item()})")
                                            
                        # 1. Slice Active Keys (Sparse Method)
                        active_k = delta_y[b, h][:, mask_h].contiguous()
                        
                        if active_k.shape[1] > 0:
                            # --- 1. TIME INNER MATMUL ---
                            torch.cuda.synchronize()
                            t_sm_start = time.time()
                            
                            active_scores = torch.matmul(regular_x[b, h].to(torch.float32), active_k.to(torch.float32))

                            torch.cuda.synchronize()
                            t_sm_end = time.time()
                            glob_set.update_latency('time_sparse_matmul', t_sm_end - t_sm_start)
                            # -----------------------------

                            delta_out[b, h, :, mask_h] = active_scores.to(delta_out.dtype)
                                
            else:
                delta_out = torch.matmul(regular_x, delta_y)

            # In-place cumsum to save memory
            delta_out = torch.cumsum(delta_out, dim=-1)

            output = self._patch_hybrid_attention(delta_out, regular_x, regular_y, bsz, seq_len, blk_size)
            
            return output


    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: Tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_value: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:

        # --- 2. TIME THE WHOLE FUNC (START) ---
        torch.cuda.synchronize()
        t_forward_start = time.time()
        # --------------------------------------

        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_value is not None:
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
        
        bsz, q_len, _ = hidden_states.size()

        keep_mask = None

        if query_states.shape[2] > 1 and globVR.delta_pf_key_on == 1:
            if globVR.use_row_delta: 
                # --- 3. TIME GET ROW DELTA ---
                torch.cuda.synchronize()
                t_rd_start = time.time()
                
                key_delta_all, keep_mask = self.get_row_delta_mat_fast(key_states, globVR.row_delta_threshold ,globVR.row_similarity_metric)
                
                torch.cuda.synchronize()
                t_rd_end = time.time()
                glob_set.update_latency('time_get_row_delta', t_rd_end - t_rd_start)
                # -----------------------------
            else:

                # --- 3B. TIME GET ELEMENT DELTA ---
                torch.cuda.synchronize()
                t_ed_start = time.time()
                
                key_delta_all = self.get_delta_mat(key_states, globVR.delta_pf_key_thresh)
                
                torch.cuda.synchronize()
                t_ed_end = time.time()
                glob_set.update_latency('time_get_delta_mat', t_ed_end - t_ed_start)

            glob_set.store_delta(globVR.delta_key, self.layer_idx, key_delta_all, globVR.collect_delta_pf_key)
            blk_size = round(q_len*globVR.scale)
            new_scale = blk_size/q_len
            if globVR.collect_delta_pf_key == 1:
                glob_set.compute_sparsity_scale(key_delta_all, new_scale, keep_mask= keep_mask)
                
            key_delta_all = repeat_kv(key_delta_all, self.num_key_value_groups)
        
        key_states = repeat_kv(key_states, self.num_key_value_groups) 
        value_states = repeat_kv(value_states, self.num_key_value_groups)


        if query_states.shape[2] > 1: 
            if globVR.delta_pf_key_on == 1:
                # --- 4. TIME DELTA MM PATTERN ---
                torch.cuda.synchronize()
                t_mm_start = time.time()
                
                attn_weights = self.regular_delta_mm_pattern_dn(key_delta_all.transpose(2,3), query_states, key_states.transpose(2,3), bsz, q_len, q_len, int(blk_size), keep_mask= keep_mask) * self.scaling
                
                torch.cuda.synchronize()
                t_mm_end = time.time()
                glob_set.update_latency('time_delta_mm_pattern', t_mm_end - t_mm_start)
                # --------------------------------
            else:

                
                attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) * self.scaling
        else:
            if globVR.delta_key_on == 1:
                attn_weights = self.regular_delta_vm_window(query_states, key_delta_all.transpose(2,3), key_states.transpose(2,3), bsz, key_states.shape[2]) * self.scaling
            else:
                attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) * self.scaling
        
        if attention_mask is not None:
            causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
            attn_weights = attn_weights + causal_mask

        attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
        attn_weights = nn.functional.dropout(attn_weights, p=0.0, training=self.training)

        attn_output = torch.matmul(attn_weights, value_states)
        attn_output = attn_output.transpose(1, 2).contiguous()

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.attn_sub_norm(attn_output) 
        attn_output = self.o_proj(attn_output)

        # --- 2. TIME THE WHOLE FUNC (END) ---
        torch.cuda.synchronize()
        t_forward_end = time.time()
        glob_set.update_latency('time_forward_total', t_forward_end - t_forward_start)
        # ------------------------------------

        return attn_output, attn_weights

class BitNetDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: BitNetConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = BitNetAttention(config=config, layer_idx=layer_idx)

        self.mlp = BitNetMLP(config)
        self.input_layernorm = BitNetRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = BitNetRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[Tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.FloatTensor, Optional[Tuple[torch.FloatTensor, torch.FloatTensor]]]:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states
        
        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states

        outputs = (hidden_states,)
        if output_attentions:
            outputs += (self_attn_weights,)

        return outputs


class BitNetRotaryEmbedding(nn.Module):
    def __init__(self, config: BitNetConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and config.rope_scaling is not None:
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


BITNET_START_DOCSTRING = r"""
    This model inherits from [`PreTrainedModel`]. Check the superclass documentation for the generic methods the
    library implements for all its model (such as downloading or saving, resizing the input embeddings, pruning heads
    etc.)

    This model is also a PyTorch [torch.nn.Module](https://pytorch.org/docs/stable/nn.html#torch.nn.Module) subclass.
    Use it as a regular PyTorch Module and refer to the PyTorch documentation for all matter related to general usage
    and behavior.

    Parameters:
        config ([`BitNetConfig`]):
            Model configuration class with all the parameters of the model. Initializing with a config file does not
            load the weights associated with the model, only the configuration. Check out the
            [`~PreTrainedModel.from_pretrained`] method to load the model weights.
"""


@add_start_docstrings(
    "The bare BitNet Model outputting raw hidden-states without any specific head on top.",
    BITNET_START_DOCSTRING,
)
class BitNetPreTrainedModel(PreTrainedModel):
    config_class = BitNetConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["BitNetDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    _supports_flex_attn = True
    _supports_cache_class = True
    _supports_quantized_cache = True
    _supports_static_cache = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, BitNetRMSNorm):
            module.weight.data.fill_(1.0)


BITNET_INPUTS_DOCSTRING = r"""
    Args:
        input_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`):
            Indices of input sequence tokens in the vocabulary. Padding will be ignored by default should you provide
            it.

            Indices can be obtained using [`AutoTokenizer`]. See [`PreTrainedTokenizer.encode`] and
            [`PreTrainedTokenizer.__call__`] for details.

            [What are input IDs?](../glossary#input-ids)
        attention_mask (`torch.Tensor` of shape `(batch_size, sequence_length) or `BlockMask`, *optional*):
            Mask to avoid performing attention on padding token indices. Mask values selected in `[0, 1]`:

            - 1 for tokens that are **not masked**,
            - 0 for tokens that are **masked**.

            If the model is configured to use flex_attention, it will attempt to convert the mask Tensor into a BlockMask,
            but you can also pass a `BlockMask` object directly here.

            [What are attention masks?](../glossary#attention-mask)

            Indices can be obtained using [`AutoTokenizer`]. See [`PreTrainedTokenizer.encode`] and
            [`PreTrainedTokenizer.__call__`] for details.

            If `past_key_values` is used, optionally only the last `input_ids` have to be input (see
            `past_key_values`).

            If you want to change padding behavior, you should read [`modeling_opt._prepare_decoder_attention_mask`]
            and modify to your needs. See diagram 1 in [the paper](https://arxiv.org/abs/1910.13461) for more
            information on the default strategy.

            - 1 indicates the head is **not masked**,
            - 0 indicates the head is **masked**.
        position_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Indices of positions of each input sequence tokens in the position embeddings. Selected in the range `[0,
            config.n_positions - 1]`.

            [What are position IDs?](../glossary#position-ids)
        past_key_values (`Cache`, *optional*):
            Pre-computed hidden-states (key and values in the self-attention blocks and in the cross-attention
            blocks) that can be used to speed up sequential decoding. This typically consists in the `past_key_values`
            returned by the model at a previous stage of decoding, when `use_cache=True` or `config.use_cache=True`.

            It is a [`~cache_utils.Cache`] instance. For more details, see our [kv cache guide](https://huggingface.co/docs/transformers/en/kv_cache).

            If `past_key_values` are used, the user can optionally input only the last `input_ids` (those that don't
            have their past key value states given to this model) of shape `(batch_size, 1)` instead of all `input_ids`
            of shape `(batch_size, sequence_length)`.
        inputs_embeds (`torch.FloatTensor` of shape `(batch_size, sequence_length, hidden_size)`, *optional*):
            Optionally, instead of passing `input_ids` you can choose to directly pass an embedded representation. This
            is useful if you want more control over how to convert `input_ids` indices into associated vectors than the
            model's internal embedding lookup matrix.
        use_cache (`bool`, *optional*):
            If set to `True`, `past_key_values` key value states are returned and can be used to speed up decoding (see
            `past_key_values`).
        output_attentions (`bool`, *optional*):
            Whether or not to return the attentions tensors of all attention layers. See `attentions` under returned
            tensors for more detail.
        output_hidden_states (`bool`, *optional*):
            Whether or not to return the hidden states of all layers. See `hidden_states` under returned tensors for
            more detail.
        return_dict (`bool`, *optional*):
            Whether or not to return a [`~utils.ModelOutput`] instead of a plain tuple.
        cache_position (`torch.LongTensor` of shape `(sequence_length)`, *optional*):
            Indices depicting the position of the input sequence tokens in the sequence. Contrarily to `position_ids`,
            this tensor is not affected by padding. It is used to update the cache in the correct position and to infer
            the complete sequence length.
"""


@add_start_docstrings(
    "The bare BitNet Model outputting raw hidden-states without any specific head on top.",
    BITNET_START_DOCSTRING,
)
class BitNetModel(BitNetPreTrainedModel):
    """
    Transformer decoder consisting of *config.num_hidden_layers* layers. Each layer is a [`BitNetDecoderLayer`]

    Args:
        config: BitNetConfig
    """

    def __init__(self, config: BitNetConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [BitNetDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = BitNetRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = BitNetRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @add_start_docstrings_to_model_forward(BITNET_INPUTS_DOCSTRING)
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **flash_attn_kwargs: Unpack[FlashAttentionKwargs],
    ) -> BaseModelOutputWithPast:
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if self.gradient_checkpointing and self.training and use_cache:
            logger.warning_once(
                "`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`."
            )
            use_cache = False

        # TODO (joao): remove this exception in v4.56 -- it exists for users that try to pass a legacy cache
        if not isinstance(past_key_values, (type(None), Cache)):
            raise ValueError("The `past_key_values` should be either a `Cache` object or `None`.")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache()

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        causal_mask = self._update_causal_mask(
            attention_mask, inputs_embeds, cache_position, past_key_values, output_attentions
        )

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # decoder layers
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            if output_hidden_states:
                all_hidden_states += (hidden_states,)

            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_ids=position_ids,
                past_key_value=past_key_values,
                output_attentions=output_attentions,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **flash_attn_kwargs,
            )

            hidden_states = layer_outputs[0]

            if output_attentions:
                all_self_attns += (layer_outputs[1],)

        hidden_states = self.norm(hidden_states)

        # add hidden states from the last decoder layer
        if output_hidden_states:
            all_hidden_states += (hidden_states,)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
        )

    def _update_causal_mask(
        self,
        attention_mask: Union[torch.Tensor, "BlockMask"],
        input_tensor: torch.Tensor,
        cache_position: torch.Tensor,
        past_key_values: Cache,
        output_attentions: bool = False,
    ):
        if self.config._attn_implementation == "flash_attention_2":
            if attention_mask is not None and (attention_mask == 0.0).any():
                return attention_mask
            return None
        if self.config._attn_implementation == "flex_attention":
            if isinstance(attention_mask, torch.Tensor):
                attention_mask = make_flex_block_causal_mask(attention_mask)
            return attention_mask

        # For SDPA, when possible, we will rely on its `is_causal` argument instead of its `attn_mask` argument, in
        # order to dispatch on Flash Attention 2. This feature is not compatible with static cache, as SDPA will fail
        # to infer the attention mask.
        past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
        using_static_cache = isinstance(past_key_values, StaticCache)

        # When output attentions is True, sdpa implementation's forward method calls the eager implementation's forward
        if self.config._attn_implementation == "sdpa" and not using_static_cache and not output_attentions:
            if AttentionMaskConverter._ignore_causal_mask_sdpa(
                attention_mask,
                inputs_embeds=input_tensor,
                past_key_values_length=past_seen_tokens,
                is_training=self.training,
            ):
                return None

        dtype = input_tensor.dtype
        sequence_length = input_tensor.shape[1]
        if using_static_cache:
            target_length = past_key_values.get_max_cache_shape()
        else:
            target_length = (
                attention_mask.shape[-1]
                if isinstance(attention_mask, torch.Tensor)
                else past_seen_tokens + sequence_length + 1
            )

        # In case the provided `attention` mask is 2D, we generate a causal mask here (4D).
        causal_mask = self._prepare_4d_causal_attention_mask_with_cache_position(
            attention_mask,
            sequence_length=sequence_length,
            target_length=target_length,
            dtype=dtype,
            cache_position=cache_position,
            batch_size=input_tensor.shape[0],
        )

        if (
            self.config._attn_implementation == "sdpa"
            and attention_mask is not None
            and attention_mask.device.type in ["cuda", "xpu", "npu"]
            and not output_attentions
        ):
            # Attend to all tokens in fully masked rows in the causal_mask, for example the relevant first rows when
            # using left padding. This is required by F.scaled_dot_product_attention memory-efficient attention path.
            # Details: https://github.com/pytorch/pytorch/issues/110213
            min_dtype = torch.finfo(dtype).min
            causal_mask = AttentionMaskConverter._unmask_unattended(causal_mask, min_dtype)

        return causal_mask

    @staticmethod
    def _prepare_4d_causal_attention_mask_with_cache_position(
        attention_mask: torch.Tensor,
        sequence_length: int,
        target_length: int,
        dtype: torch.dtype,
        cache_position: torch.Tensor,
        batch_size: int,
        **kwargs,
    ):
        """
        Creates a causal 4D mask of shape `(batch_size, 1, query_length, key_value_length)` from a 2D mask of shape
        `(batch_size, key_value_length)`, or if the input `attention_mask` is already 4D, do nothing.

        Args:
            attention_mask (`torch.Tensor`):
                A 2D attention mask of shape `(batch_size, key_value_length)` or a 4D attention mask of shape
                `(batch_size, 1, query_length, key_value_length)`.
            sequence_length (`int`):
                The sequence length being processed.
            target_length (`int`):
                The target length: when generating with static cache, the mask should be as long as the static cache,
                to account for the 0 padding, the part of the cache that is not filled yet.
            dtype (`torch.dtype`):
                The dtype to use for the 4D attention mask.
            cache_position (`torch.Tensor`):
                Indices depicting the position of the input sequence tokens in the sequence.
            batch_size (`torch.Tensor`):
                Batch size.
        """
        if attention_mask is not None and attention_mask.dim() == 4:
            # In this case we assume that the mask comes already in inverted form and requires no inversion or slicing.
            causal_mask = attention_mask
        else:
            min_dtype = torch.finfo(dtype).min
            causal_mask = torch.full(
                (sequence_length, target_length), fill_value=min_dtype, dtype=dtype, device=cache_position.device
            )
            if sequence_length != 1:
                causal_mask = torch.triu(causal_mask, diagonal=1)
            causal_mask *= torch.arange(target_length, device=cache_position.device) > cache_position.reshape(-1, 1)
            causal_mask = causal_mask[None, None, :, :].expand(batch_size, 1, -1, -1)
            if attention_mask is not None:
                causal_mask = causal_mask.clone()  # copy to contiguous memory for in-place edit
                mask_length = attention_mask.shape[-1]
                padding_mask = causal_mask[:, :, :, :mask_length] + attention_mask[:, None, None, :].to(
                    causal_mask.device
                )
                padding_mask = padding_mask == 0
                causal_mask[:, :, :, :mask_length] = causal_mask[:, :, :, :mask_length].masked_fill(
                    padding_mask, min_dtype
                )

        return causal_mask


class KwargsForCausalLM(FlashAttentionKwargs, LossKwargs): ...


class BitNetForCausalLM(BitNetPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = None
    _pp_plan = None

    def __init__(self, config):
        super().__init__(config)
        self.model = BitNetModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    def get_output_embeddings(self):
        return self.lm_head

    def set_output_embeddings(self, new_embeddings):
        self.lm_head = new_embeddings

    def set_decoder(self, decoder):
        self.model = decoder

    def get_decoder(self):
        return self.model

    @can_return_tuple
    @add_start_docstrings_to_model_forward(BITNET_INPUTS_DOCSTRING)
    @replace_return_docstrings(output_type=CausalLMOutputWithPast, config_class=_CONFIG_FOR_DOC)
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[KwargsForCausalLM],
    ) -> CausalLMOutputWithPast:
        r"""
        Args:
            labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Labels for computing the masked language modeling loss. Indices should either be in `[0, transformers.,
                config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
                (masked), the loss is only computed for the tokens with labels in `[0, transformers., config.vocab_size]`.

        Returns:

        Example:

        ```python
        >>> from transformers import AutoTokenizer, BitNetForCausalLM

        >>> model = BitNetForCausalLM.from_pretrained("microsoft/bitnet-b1.58-2B-4T")
        >>> tokenizer = AutoTokenizer.from_pretrained("microsoft/bitnet-b1.58-2B-4T")

        >>> prompt = f'<|begin_of_text|>User: Hey, are you conscious? Can you talk to me?<|eot_id|>Assistant: '
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=100)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "User: Hey, are you conscious? Can you talk to me?Assistant: No, I'm not conscious. I'm an artificial intelligence designed to assist with information and tasks. How can I help you today?"
        ```"""
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


__all__ = ["BitNetForCausalLM", "BitNetModel", "BitNetPreTrainedModel"]
